### ISSUE TITLE
Server crashes after client connection

### ISSUE THREAD

**Issue by it-praktyk** [cortexm/ser2tcp#1]
On the console server what is run using Raspberry Pi 3 and Raspbian GNU/Linux 8 I run, Python version 2.7.9

```
root@piconsoleserver3:/home/pi/ser2tcp# python ser2tcp.py /dev/ttyUSB0 115200 NONE ONE -l 0:10001 -v -t
2017-04-26 10:26:14,062 Starting server (listen: 0:10001, serial: /dev/ttyUSB0:115200)..
2017-04-26 10:26:18,171 Serial /dev/ttyUSB0 connected
2017-04-26 10:26:18,178 Client connected: 10.1.3.147:49022
must be string or buffer, not list
2017-04-26 10:26:18,186 Exiting..
2017-04-26 10:26:18,190 Client disconnected: 10.1.3.147:49022
2017-04-26 10:26:18,291 Serial /dev/ttyUSB0 disconnected
Traceback (most recent call last):
  File "ser2tcp.py", line 286, in <module>
    main()
  File "ser2tcp.py", line 277, in main
    raise err
TypeError: must be string or buffer, not list
2017-04-26 10:26:18,337 Exiting..
root@piconsoleserver3:/home/pi/ser2tcp# 
```

On the console client - Ubuntu 16.04 
```
/foldername telnet -8 piconsoleserver3.example.com 10001
Trying 10.1.3.22...
Connected to piconsoleserver3.example.com.
Escape character is '^]'.
Connection closed by foreign host.
```

```
Help on package serial:

NAME
    serial

FILE
    /usr/lib/python2.7/dist-packages/serial/__init__.py

DESCRIPTION
    # portable serial port access with python
    # this is a wrapper module for different platform implementations
    #
    # (C) 2001-2010 Chris Liechti <cliechti@gmx.net>
    # this is distributed under a free software license, see license.txt
```

I tried connection from Windows machine too - I used Putty on Windows 10.

**Comment by it-praktyk** [comment]
When I run ser2tcp using Python 3.4.2 I see

```
root@piconsoleserver3:/home/pi/ser2tcp-python# python3 ser2tcp.py /dev/ttyUSB0 115200 NONE ONE -l 0:10001 -v -t
2017-04-26 11:33:30,136 Starting server (listen: 0:10001, serial: /dev/ttyUSB0:115200)..
2017-04-26 11:33:49,031 Serial /dev/ttyUSB0 connected
2017-04-26 11:33:49,041 Client connected: 10.1.3.147:49946
'list' does not support the buffer interface
2017-04-26 11:33:54,779 Exiting..
2017-04-26 11:33:54,784 Client disconnected: 10.1.3.147:49946
2017-04-26 11:33:54,881 Serial /dev/ttyUSB0 disconnected
Traceback (most recent call last):
  File "ser2tcp.py", line 286, in <module>
    main()
  File "ser2tcp.py", line 277, in main
    raise err
  File "ser2tcp.py", line 274, in main
    ser2tcp.process()
  File "ser2tcp.py", line 221, in process
    con.on_received(data)
  File "ser2tcp.py", line 97, in on_received
    self._serial.write(data)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 475, in write
    n = os.write(self.fd, d)
TypeError: 'list' does not support the buffer interface
2017-04-26 11:33:54,973 Exiting..
```

Server crashes when I use 'Enter'
```
root@e108041-lin:/home/wojsci01/Documents/ConsoleServer# telnet -E piconsoleserver3.example.com 10001
Trying 10.1.134.22...
Connected to piconsoleserver3.example.com.
Escape character is 'off'.
Connection closed by foreign host.
root@e108041-lin:/home/wojsci01/Documents/ConsoleServer# 
```

```
Help on package serial:

NAME
    serial

DESCRIPTION
    # portable serial port access with python
    # this is a wrapper module for different platform implementations
    #
    # (C) 2001-2010 Chris Liechti <cliechti@gmx.net>
    # this is distributed under a free software license, see license.txt
```

**Comment by pavelrevak** [comment]
Thanks for reporting, there is no support for python 2.x, only 3.x.
but personally I tested this only with python 3.5 and 3.6 and on MAC OS.
So, I make some tests also with Linux.

**Comment by it-praktyk** [comment]
We added based on http://stackoverflow.com/questions/37802078/raspberry-pi-serial-communication-python-write-command-issue - below the line 96

```
if data:
    ba=bytearray(data)
    self._serial.write(ba)
```

Server doesn't crash, we can type in console, it looks like working now.

**Comment by pavelrevak** [comment]
I see the difference:
pyserial in debian is quite old with version 2.6 (package: python3-serial)
and on MAC OS I have actually installed with pip more recent version: pyserial 3.2.1
can you please check your pyserial version?

>>> import serial
>>> serial.VERSION

**Comment by pavelrevak** [comment]
probably it is this:
https://github.com/pyserial/pyserial/blob/master/CHANGES.rst
### Version 2.7 2013-10-17
- Ensure working with bytes in write() calls

**Comment by it-praktyk** [comment]
```
root@piconsoleserver3:/home/pi/ser2tcp-python# python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.VERSION
'2.6'
```

```
root@piconsoleserver3:/home/pi/ser2tcp-python# apt-cache show python3-serial
Package: python3-serial
Source: pyserial
Version: 2.6-1.1
Installed-Size: 281
Maintainer: Matthias Klose <doko@debian.org>
Architecture: all
Depends: python3:any (>= 3.3.2-2~), python3
Suggests: python3-wxgtk3.0 | python3-wxgtk
Size: 49966
SHA256: f9180e561634b15c0f76208da569f5faf08c0531f2fc64ddda2034a3926b0e43
SHA1: 02c160e4bc20e24ddb1cb075faf0e3dcd4de1242
MD5sum: e0efa358904e1a8412cd4c4282bcdb74
Description: pyserial - module encapsulating access for the serial port
 This module encapsulates the access for the serial port. It provides
 back-ends for standard Python running on Windows, Linux, BSD (possibly
 any POSIX compliant system). The module named "serial" automatically
 selects the appropriate back-end.
Description-md5: 4dab91c4e71dab549f66bda57e2ecc69
Homepage: http://pyserial.sourceforge.net/
Section: python
Priority: optional
Filename: pool/main/p/pyserial/python3-serial_2.6-1.1_all.deb

```

**Comment by pavelrevak** [comment]
I prefer to not convert bytearray, better is to use recent pyserial (from pip)

**Comment by pavelrevak** [comment]
My Debian (raspberry pi)
install pyserial from repository:
```
$ sudo apt-get upgrade python3-serial
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  python3-serial
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 50.0 kB of archives.
After this operation, 288 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ftp.sk.debian.org/debian/ jessie/main python3-serial all 2.6-1.1 [50.0 kB]
Fetched 50.0 kB in 0s (233 kB/s)
Selecting previously unselected package python3-serial.
(Reading database ... 21118 files and directories currently installed.)
Preparing to unpack .../python3-serial_2.6-1.1_all.deb ...
Unpacking python3-serial (2.6-1.1) ...
Setting up python3-serial (2.6-1.1) ...
```
test it:
```
$ python3 ser2tcp.py /dev/ttyAMA0 115200 EVEN -l 0:10001 -t -v
2017-04-27 08:13:09,488 Starting server (listen: 0:10001, serial: /dev/ttyAMA0:115200)..
2017-04-27 08:13:14,861 Serial /dev/ttyAMA0 connected
2017-04-27 08:13:14,864 Client connected: 127.0.0.1:36996
'list' does not support the buffer interface
2017-04-27 08:13:17,843 Exiting..
2017-04-27 08:13:17,844 Client disconnected: 127.0.0.1:36996
2017-04-27 08:13:17,845 Serial /dev/ttyAMA0 disconnected
Traceback (most recent call last):
  File "ser2tcp.py", line 286, in <module>
    main()
  File "ser2tcp.py", line 277, in main
    raise err
  File "ser2tcp.py", line 274, in main
    ser2tcp.process()
  File "ser2tcp.py", line 221, in process
    con.on_received(data)
  File "ser2tcp.py", line 97, in on_received
    self._serial.write(data)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 475, in write
    n = os.write(self.fd, d)
TypeError: 'list' does not support the buffer interface
2017-04-27 08:13:17,879 Exiting..
```
So, I have same issue,
remove pyserial
```
$ sudo apt-get purge python3-serial
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  python3-serial*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 288 kB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 21145 files and directories currently installed.)
Removing python3-serial (2.6-1.1) ...
```
install from pip:
```
$ sudo pip3 install pyserial
Downloading/unpacking pyserial
  Downloading pyserial-3.3-py2.py3-none-any.whl (189kB): 189kB downloaded
Installing collected packages: pyserial
Successfully installed pyserial
Cleaning up...
$ sudo python3 ser2tcp.py /dev/ttyAMA0 115200 EVEN -l 0:10001 -t -v
2017-04-27 08:18:24,772 Starting server (listen: 0:10001, serial: /dev/ttyAMA0:115200)..
2017-04-27 08:18:27,070 Serial /dev/ttyAMA0 connected
2017-04-27 08:18:27,072 Client connected: 127.0.0.1:37102
^C2017-04-27 08:18:31,998 Exiting..
2017-04-27 08:18:31,999 Client disconnected: 127.0.0.1:37102
2017-04-27 08:18:32,001 Serial /dev/ttyAMA0 disconnected
2017-04-27 08:18:32,002 Exiting..
```
without problems

**Comment by pavelrevak** [comment]
conclusion is to use recent version of pyserial (at lest v2.7)
